name = "BentleyOttmann"
uuid = "8ddd4dee-9780-47b0-8411-bdd780c27350"
authors = ["Arnau Quera-Bofarull <arnauq@protonmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
